language: python
cache: pip

matrix:
  include:
    - env: TOXENV="py27-dj{18,19,110,111}"
      python: '2.7'
    - env: TOXENV="py34-dj{18,19,110,111,20}"
      python: '3.4'
    - env: TOXENV="py35-dj{18,19,110,111,20}"
      python: '3.5'
    - env: TOXENV="py36-dj{18,19,110,111,20}"
      python: '3.6'
    - env: |
        TOXENV="py36-dj{111,20}-postgres"
        DATABASE_URL="postgres://postgres@localhost/database"
      python: '3.6'
      services:
        - postgresql
    - env: |
        TOXENV="py36-dj{111,20}-mysql"
        DATABASE_URL="mysql://travis@127.0.0.1/database"
      python: '3.6'
      services:
        - mysql
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - env
  - tox
