language: python
cache: pip

services:
  - postgresql

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost/database"

matrix:
  include:
    - env: TOXENV="py27-dj{18,19,110,111}-postgres"
      python: '2.7'
    - env: TOXENV="py34-dj{18,19,110,111,20}-postgres"
      python: '3.4'
    - env: TOXENV="py35-dj{18,19,110,111,20}-postgres"
      python: '3.5'
    - env: TOXENV="py36-dj{18,19,110,111,20}-postgres"
      python: '3.6'
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - env
  - tox
