language: python
cache: pip

env:
  - DJANGO_SETTINGS_MODULE="tests.settings"

matrix:
  include:
    - env: TOXENV="py27-dj{18,19,110,111}"
      python: '2.7'
    - env: TOXENV="py34-dj{18,19,110,111,20}"
      python: '3.4'
    - env: TOXENV="py35-dj{18,19,110,111,20}"
      python: '3.5'
    - env: TOXENV="py36-dj{18,19,110,111,20}"
      python: '3.6'
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - tox
